name: mibilib
channels:
- conda-forge
- defaults
dependencies:
# versions for the mibilib conda environment are set here
- python=3.11.*
- pip
- git # mibilib donwload and deployment
- matplotlib
- numpy
- pandas
- pillow
- pytest # used for testing only
- scikit-image
- scikit-learn
- tifffile
- tqdm
- pip:
  - git+https://github.com/christianrickert/mibilib@master
