name: mibilib
channels:
- conda-forge
- defaults
dependencies:
- python=3.11.*
- pip
- matplotlib
- numpy
- pandas
- pillow
- pytest
- scikit-image
- scikit-learn
- tifffile
- tqdm
- pip:
  - git+https://github.com/christianrickert/mibilib@simplify_installation
